[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.softdab.tech; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' *.softdab.tech;"

[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "</assets/css/main.css>; rel=preload; as=style, </assets/js/main.js>; rel=preload; as=script"
    Cache-Control = "public, max-age=0, must-revalidate"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"